### ISSUE TITLE
Meta task to move to github installation profile

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/signage.uiowa.edu#1]
- [x] Migrate away from CAS to Shib.
- [x] Rm CAS-related modules from repo
- [x] Rm LDAP-related modules from repo
- [x] Add modules to system.make file
```
  bongo:
    version: '1.0-beta3'
    subdir: 'contrib'
  localist_pane:
    subdir: 'custom'
    download:
      url: https://github.com/ITS-UofIowa/localist_pane.git
      tag: '7.x-1.4'
  masquerade:
    version: '1.0-rc7'
    subdir: 'contrib'
  memcache:
    version: '1.5'
    subdir: 'contrib'
  simplesamlphp_auth:
    subdir: 'contrib'
    download:
      branch: '7.x-3.x'
      revision: '6e92be67b007e4e9f4a071b9a82c7db8fbcee2af'
    patch:
      - 'https://www.drupal.org/files/issues/simplesamlphp_auth-store-saml-roles-separate-2707269-2.patch'
  uiowa_acquia_authentication:
    subdir: 'custom'
    download:
      url: git@github.com:ITS-UofIowa/uiowa_acquia_authentication.git
      tag: '7.x-1.11'
  uiowa_signage_modules:
    subdir: 'custom'
    download:
      url: git@github.com:ITS-UofIowa/uiowa_signage_modules.git
      branch: 'master'
```

- [x] Migrate webmaster users to editor role (since webmaster role now has elevated panelizer-based configuration). Closing in favor of #3.

- [x] Featurize panelizer config in this repo. Closing in favor of #8.
- [x]  SSL
